# Generated by Django 6.0.2 on 2026-02-06 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='fas fa-heart', max_length=50, verbose_name='Иконка (Font Awesome)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название активности')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('price', models.IntegerField(verbose_name='Стоимость в Аринкойнах')),
                ('image', models.ImageField(upload_to='activities/', verbose_name='Картинка')),
                ('duration', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('location', models.CharField(max_length=200, verbose_name='Место')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='arynchoice.category')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arincoins', models.IntegerField(default=100, verbose_name='Аринкойны')),
                ('is_special_user', models.BooleanField(default=False, verbose_name='Особый доступ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Пожелания/комментарии')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arynchoice.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выбор',
                'verbose_name_plural': 'Выборы',
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
