# Generated by Django 6.0.2 on 2026-02-12 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arynchoice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('coins_reward', models.IntegerField(verbose_name='Награда в Аринкойнах')),
                ('icon', models.CharField(default='fas fa-trophy', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='EarnMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reward', models.IntegerField(verbose_name='Награда в Аринкойнах')),
                ('icon', models.CharField(default='fas fa-coins', max_length=50, verbose_name='Иконка')),
                ('instructions', models.TextField(blank=True, help_text='Что нужно сделать, чтобы получить награду', verbose_name='Инструкция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Метод заработка',
                'verbose_name_plural': 'Методы заработка',
                'ordering': ['-is_active', '-reward'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_operations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидает проверки'), ('approved', '✅ Выполнено'), ('rejected', '❌ Отклонено'), ('cancelled', '🚫 Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('proof_text', models.TextField(blank=True, help_text='Ссылка, скриншот или описание', verbose_name='Текст подтверждения')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('coins_awarded', models.IntegerField(default=0, verbose_name='Начислено Аринкойнов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arynchoice.earnmethod', verbose_name='Метод')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_earn_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на заработок',
                'verbose_name_plural': 'Заявки на заработок',
                'ordering': ['-created_at'],
            },
        ),
    ]
