# Generated by Django 6.0.2 on 2026-02-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arynchoice', '0002_achievement_earnmethod_cointransaction_earnrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selection',
            options={'ordering': ['-selected_at'], 'verbose_name': 'Выбор', 'verbose_name_plural': 'Выборы'},
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set(),
        ),
    ]
